# Copyright FMJ Studios
# SPDX-License-Identifier: MIT

apiVersion: v2
appVersion: 2.20.6
kubeVersion: ">=1.26.0-0"
name: paperless-ngx
version: 0.3.0
dependencies:
  - name: postgresql
    repository: oci://registry-1.docker.io/bitnamicharts
    condition: postgresql.enabled
    version: ~15.5
  - name: redis
    repository: oci://registry-1.docker.io/bitnamicharts
    condition: redis.enabled
    version: ~19.5
  - name: tika
    repository: https://apache.jfrog.io/artifactory/tika
    condition: tika.enabled
    version: ~2.9
  - name: gotenberg
    repository: https://koifresh.github.io/helm-charts
    condition: gotenberg.enabled
    version: ~0.2.2
description: Paperless-NGX is a community-supported supercharged version of paperless - scan, index and archive all your physical documents
home: https://github.com/paperless-ngx/paperless-ngx
icon: https://raw.githubusercontent.com/fmjstudios/artwork/76af35c64fd93c12e851925b0d3801e89978f05a/projects/paperless-ngx/icon/color/paperless-ngx-icon-color.png
keywords:
  - documents
  - archival
  - ocr
  - conversion
  - paper
  - paperless
sources:
  - "https://github.com/koifresh/helm-charts"
maintainers:
  - name: KoiFresh
    email: kai@mayer.sh
