# Copyright FMJ Studios
# SPDX-License-Identifier: MIT

apiVersion: v2
appVersion: 8.27.0
kubeVersion: ">=1.26.0-0"
name: gotenberg
version: 0.2.4
description: Gotenberg is a Docker-powered stateless API for PDF files.
home: https://gotenberg.dev/
icon: https://user-images.githubusercontent.com/8983173/130322857-185831e2-f041-46eb-a17f-0a69d066c4e5.png
keywords:
  - documents
  - conversion
  - pdf
  - office
  - html
  - markdown
sources:
  - "https://github.com/koifresh/helm-charts"
maintainers:
  - name: KoiFresh
    email: kai@mayer.sh
